### PR TITLE
fix depwarn and set minimum julia version to 0.4

### PR DESCRIPTION
**Pull request by visr**
Started off by fixing a deprecation warning, a single `symbol` -> `Symbol`. Noticed this failed tests on 0.3 so I proceeded to set the minimum version to 0.4.

If 0.3 is still needed I can also just use `@compat Symbol(...)`. But this cleans up as well.

### CODE REVIEW

**Comment by visr** [comment]
@yeesian (or others) are you ok with dropping julia v0.3 support (also for other JuliaGeo packages)? Just want to get a thumbs up before I merge this.

**Comment by yeesian** [comment]
:+1:

Can you help tag and provide a new release when/after you merge this?

**Comment by c42f** [comment]
:+1: totally ok with dropping 0.3 support.

**Comment by visr** [comment]
New release, GeoJSON 0.1.0, is in METADATA. Needed to be a minor version bump because we drop julia 0.3 support.

**Pull request merged**
