### PR TITLE
Fix final 0.4 deprecation warnings

### PR DESCRIPTION
**Pull request by visr**
Also run Travis on 0.3 and use Compat in tests.

### CODE REVIEW

**Comment by visr** [comment]
Failing on 0.3.
```
INFO: Testing GeoJSON
ERROR: `dict2geojson` has no method matching dict2geojson(::Nothing)
 in dict2geojson at /home/travis/.julia/v0.3/GeoJSON/src/parser.jl:8
 in parse at /home/travis/.julia/v0.3/GeoJSON/src/parser.jl:72
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/travis/.julia/v0.3/GeoJSON/test/runtests.jl, in expression starting on line 5
```

Can get back to it later. What is the plan for dropping 0.3 support?

**Comment by yeesian** [comment]
Apologies for the lack of activity on this package: I have a local branch that implements (and uses) the GeoInterface package, but didn't want to force the dependency. I can push it if you're interested.

1. The fix is to add `dict2geojson(obj::Void) = nothing` to `parser.jl`
2. We should support v0.3 on this PR (because of #7), merge to master and tag in METADATA, before dropping support (so GeoJSON v0.0.3 will be the last version to support for 0.3)

**Comment by visr** [comment]
Sounds good to me. Thanks for the tip on `@compat`, I assumed that would have been taken care of by `using Compat`. Now it's passing on 0.3, I'm done.

**Comment by yeesian** [comment]
Thanks!

**Pull request merged**
