### PR TITLE
fixes the update to JSON v0.6

### PR DESCRIPTION
**Pull request by yeesian**
ref: https://github.com/JuliaLang/METADATA.jl/pull/5398

I seem to be running into issues with the package management system. @TotalVerb or @tkelman, can you help check if this fixes the issue?

### CODE REVIEW

**Comment by tkelman** [comment]
What kind of issues? I'm inclined to trust Travis `INFO: Installing JSON v0.6.0` - maybe restart the last build you had on master without this PR to verify it fails without this fix?

**Comment by yeesian** [comment]
> What kind of issues?

```julia
julia> Pkg.test("GeoJSON")
INFO: Computing test dependencies for GeoJSON...
ERROR: ASTInterpreter can't be installed because it has no versions that support 0.4.2 of julia. You may need to update METADATA by running `Pkg.update()`
 in error at error.jl:22
 in resolve at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in test! at pkg/entry.jl:769
 in test at pkg/entry.jl:797
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
```

I don't have ASTInterpreter installed, and can't trace down any package that has a dependency on it.

**Comment by tkelman** [comment]
Do you have Atom checked out? Check `Pkg.status()` and run `Pkg.free("Atom")` or any other packages you have checked out to master that maybe shouldn't be

**Comment by yeesian** [comment]
> What kind of issues? I'm inclined to trust Travis INFO: Installing JSON v0.6.0 - maybe restart the last build you had on master without this PR to verify it fails without this fix?

```
yeesian at YeeSian-MacBookPro in ~/.julia/v0.4/GeoJSON/test on master [$]
$ julia runtests.jl
ERROR: LoadError: MethodError: `dict2geojson` has no method matching dict2geojson(::Dict{UTF8String,Any})
 in parse at /Users/yeesian/.julia/v0.4/GeoJSON/src/parser.jl:72
 in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in process_options at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/yeesian/.julia/v0.4/GeoJSON/test/runtests.jl, in expression starting on line
```

**Comment by yeesian** [comment]
> Do you have Atom checked out? Check Pkg.status() and run Pkg.free("Atom") or any other packages you have checked out to master that maybe shouldn't be

That was it. Thanks! (:

**Pull request merged**
