### PR TITLE
add basic documentation

### PR DESCRIPTION
**Pull request by rafaqz**
Set up documentation, and tweak the current docs a little.

### CODE REVIEW

**Review by visr — APPROVED** [review]
Thanks for setting this up. Would be nice to add the Readme text and quickstart to the docs as well, but we can also do that later. I pushed some minor edits.

**Comment by rafaqz** [comment]
Thanks for the edits. The readme also doubles as the module docs now.

**Comment by rafaqz** [comment]
Are you happy to register v0.6 when this is merged?

**Comment by visr** [comment]
Yeah let's register it. Not sure how to write an upgrade guide much better than "everything changed, look at the new docs". The README still needs a link to the docs.

**Comment by visr** [comment]
Neat trick to add the readme as module docs by the way, it looks much better now: https://juliageo.org/geojson.jl/dev/.

**Pull request merged**
